[MP-18] Slider component v2
Touch-ofTech/touch-of-tech-storybook pull request #21
Opened 2022-11-29 19:52 UTC by thisisofficial

### Description

Added an image slider with customizable image backgrounds and titles.
![image](https://user-images.githubusercontent.com/93210838/204072405-e8508920-304c-428f-9091-e42b7de144ea.png)

### Testing Checklist

- [ ] Test cases have been added/updated
- [x] Tested locally in browser (at least one other than Chrome)
- [x] All tests pass

### What JIRA Ticket(s) does this PR address?

- [MP-18](https://cd95.atlassian.net/browse/MP-18)

2022-11-29 19:53 UTC, thisisofficial commented
@caarlosdamian Review please

2022-12-27 23:23 UTC, thisisofficial commented
Review again please, this has been long overdue

2022-12-28 04:11 UTC, caarlosdamian requested changes
check

2022-12-28 04:11 UTC, caarlosdamian commented on src/components/imageCarousel/ImageSlider.tsx
> +              {' '}
remove this

2022-12-28 04:11 UTC, caarlosdamian commented on src/components/imageCarousel/imageSlider.css
> +  /* transform: translate(-800px); */
remove this

2022-12-28 04:11 UTC, caarlosdamian commented on src/components/imageCarousel/imageSlider.css
> +.circle{
why do you have this class????

2022-12-28 04:11 UTC, caarlosdamian commented on src/components/imageCarousel/imageSlider.css
> +.circle2{
why do you have this class???? remove if you dont use it

2022-12-28 20:15 UTC, caarlosdamian approved these changes

2022-12-28 20:15 UTC, merged