[MP-23]Navigation section component
Touch-ofTech/touch-of-tech-storybook pull request #28
Opened 2022-12-29 05:45 UTC by thisisofficial

PR checklist

### Description

Added a navigation component that can be edited with simple props
![image](https://user-images.githubusercontent.com/93210838/209908416-a4716bdf-6950-4c25-80ed-721903c53232.png)

### Testing Checklist

- [ ] Test cases have been added/updated
- [x] Tested locally in browser (at least one other than Chrome)
- [x] All tests pass

### What JIRA Ticket(s) does this PR address?

- [MP-23](https://cd95.atlassian.net/browse/MP-23)

2022-12-29 19:32 UTC, thisisofficial commented
@caarlosdamian review please

2022-12-31 09:46 UTC, thisisofficial commented
Review request bump @caarlosdamian please

2023-01-02 04:26 UTC, caarlosdamian requested changes
some comments

2023-01-02 04:26 UTC, caarlosdamian commented on src/components/navigation/navigation.css
> +
remove space

2023-01-05 05:04 UTC, caarlosdamian approved these changes

2023-01-05 05:05 UTC, merged