feat: Reusable Grid component
Touch-ofTech/touch-of-tech-storybook pull request #9
Opened 2022-11-03 03:00 UTC by thisisofficial

### Description

Created a reusable grid container component with custom props.

Added it's corresponding interactive storybook.
![image](https://user-images.githubusercontent.com/93210838/199639689-4d11b949-7e6b-49fa-9034-8f2ae8888749.png)

### Testing Checklist

- [ ] Test cases have been added/updated
- [x] Tested locally in browser (at least one other than Chrome)
- [x] All tests pass

### What JIRA Ticket(s) does this PR address?

- [MP-10](https://cd95.atlassian.net/browse/MP-10)

2022-11-03 05:06 UTC, caarlosdamian requested changes
add tests as well

2022-11-03 05:06 UTC, caarlosdamian commented on src/components/grid/Grid.tsx
> +  children?: ReactNode;
this is not optional 
gap is not optional
template_columns is not optional 
className is optional

2022-11-03 05:06 UTC, caarlosdamian commented on src/components/grid/grid.css
> +}
add a line a the end of the file

2022-11-03 23:55 UTC, thisisofficial commented
Tests added, please check.

2022-11-04 13:48 UTC, caarlosdamian approved these changes
lgtm

2022-11-04 13:49 UTC, merged